### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by yyt520** [xjh22222228/egg-mailer#1]
app.js中只是定义了一个Mail类，那如何保证Mail类中的构造函数执行，不需要new一个新的对象吗

**Comment by yyt520** [comment]
如何确保controller中this.config生效

**Comment by liuzi6612** [comment]
@yyt520 不需要new，参照文档步骤就可以了

**Comment by yyt520** [comment]
> @yyt520 不需要new，参照文档步骤就可以了

没有啊，我就是在代码service里面用 结果报错了 显示    from: this.config.mailer.auth.user, 这一行的mailer未定义，我感觉就是并没有挂载到app上    还希望您能帮我解答下    （我记得构造函数必须new 才会生效吧   ）  方便加下微信吗  我想请教您一下

**Comment by yyt520** [comment]
今天有点晚  ，明天可以回复我一下吗 拜托啦

**Comment by liuzi6612** [comment]
@yyt520 按照文档步骤不会有问题，如果不行提供一个最小复现仓库

**Comment by yyt520** [comment]
您能给我讲讲构造函数是如何生效的吗  按理来说类Mail没有创建实例 构造函数不会生效的呀 ， 希望您能说一下
