### ISSUE TITLE
优化一些内容

### ISSUE THREAD

**Issue by ddzyan** [xjh22222228/egg-mailer#2]
采用 addSingleton 加载对象，从而支持用户配置多个 nodemialer 对象进行使用
加载过程增加 coreLogger 日志输出到核心插件日志中，方便评估加载进度
增加单元测试，方便持续集成测试

**Comment by liuzi6612** [comment]
您可以提PR吗

**Comment by ddzyan** [comment]
> 您可以提PR吗

好的，我这提交了，麻烦看下哈，增加了workflow的持续集成和上面说的一些优化，这个模块测试过，需要Nodejs10.x版本以上才能支持

**Comment by ddzyan** [comment]
> > 您可以提PR吗
> 
> 好的，我这提交了，麻烦看下哈，增加了workflow的持续集成和上面说的一些优化，这个模块测试过，需要Nodejs10.x版本以上才能支持

https://github.com/xjh22222228/egg-mailer/pull/3

**Comment by ddzyan** [comment]
@xjh22222228 可以的麻烦 npm 重新发布一个模块包版本

**Comment by liuzi6612** [comment]
已发布
