### ISSUE TITLE
npm 模块包版本提升下哈

### ISSUE THREAD

**Issue by ddzyan** [xjh22222228/egg-mailer#5]
现在还是老版本号

**Comment by liuzi6612** [comment]
已经是最新了

**Comment by ddzyan** [comment]
![image](https://user-images.githubusercontent.com/9130123/117652167-6c627e80-b1c5-11eb-9405-91704c4f36b2.png)
最新合并的内容还没发版吧？麻烦操作下哈

**Comment by liuzi6612** [comment]
ok了
